[package]
name = "ean-wasm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.80"
ean = "0.2.0"
js-sys = "0.3.51"

[lib]
crate-type = ["cdylib", "rlib"]
